{% set name = "dm-tree" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/tree/archive/{{ version }}.tar.gz
  sha256: 6776404b23b4522c01012ffb314632aba092c9541577004ab153321e87da439a
  patches:
    - patches/0001-Internal-change.patch
    - patches/0002-Removed-a-dependency-on-six.patch
    - patches/0003-Internal-change.patch
    - patches/0004-Change-implementation-of-map_structure_with_path_up_.patch
    - patches/0005-Add-recipes-with-doctests.-These-will-help-implement.patch
    - patches/0006-Add-more-tests-for-map_structure_up_to.patch
    - patches/0007-Small-refactor-to-make-planned-implementation-change.patch
    - patches/0008-Remove-accidentally-included-invalid-dependency.patch
    - patches/0009-Internal-change.patch
    - patches/0010-Add-tree-recipe-to-broadcast-a-value-across-a-refere.patch
    - patches/0011-Update-docs-copyright-year-dynamically.patch
    - patches/0012-Migrate-to-CMake-build-system-and-set-up-cibuildwhee.patch
    - patches/0013-Removed-unused-imports.patch
    - patches/0014-Add-test-to-cover-mapping-custom-classes-with-paths.patch
    - patches/0015-Temporarily-remove-optimisation-which-is-causing-iss.patch
    - patches/0016-Internal-Changes.patch
    - patches/0017-Build-Python-3.10-wheels-and-arm64-universal2-wheels.patch
    - patches/0018-Improve-error-message.patch
    - patches/0019-Support-keyword-only-attrs-based-structures.patch
    - patches/0020-Removed-pytype-disable-not-supported-yet-as-pytype-d.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - cmake
    - make
    - setuptools
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - tree
  commands:
    - python -m unittest tree.tree_test tree.tree_benchmark
  requires:
    - attrs
    - absl-py
    - numpy
    - wrapt

about:
  home: https://github.com/deepmind/tree
  summary: Tree is a library for working with nested data structures.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    tree is a library for working with nested data structures.
    In a way, tree generalizes the builtin map function which only supports flat sequences, and allows to apply a function to each "leaf" preserving the overall structure.

  doc_url: https://tree.readthedocs.io/en/stable/
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - vnlitvinov
    - maresb
