{% set name = "dm-tree" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dm-tree-{{ version }}.tar.gz
  sha256: 6776404b23b4522c01012ffb314632aba092c9541577004ab153321e87da439a
  patches:
#     - patches/0001-Contain-bazel-root.patch
    - patches/upstream-pr-58.patch
    - patches/upstream-pr-72.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # script: '"%RECIPE_DIR%\windows.bat" "{{ PYTHON }}"'  # [win]


# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - cmake
    - make
    - setuptools
   # - bazel <4
   # - m2-patch  # [win]
  host:
    - pip
    - python
    - six >=1.12.0 # needed because we can install by "python setup.py install" which has no --no-deps switch
  run:
    - python
    - six >=1.12.0

test:
  imports:
    - tree
  commands:
    - python -m unittest tree.tree_test tree.tree_benchmark
  requires:
    - attrs
    - absl-py
    - numpy
    - wrapt

about:
  home: https://github.com/deepmind/tree
  summary: Tree is a library for working with nested data structures.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    tree is a library for working with nested data structures.
    In a way, tree generalizes the builtin map function which only supports flat sequences, and allows to apply a function to each "leaf" preserving the overall structure.

  doc_url: https://tree.readthedocs.io/en/stable/
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - vnlitvinov
    - maresb
