{% set version = "0.1.8" %}

package:
  name: dm-tree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dm-tree/dm-tree-{{ version }}.tar.gz
  sha256: 0fcaabbb14e7980377439e7140bd05552739ca5e515ecb3119f234acee4b9430

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - cmake
    - make
    - setuptools
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - tree
  commands:
    - python -m unittest tree.tree_test tree.tree_benchmark
  requires:
    - attrs
    - absl-py
    - numpy
    - wrapt

about:
  home: https://github.com/deepmind/tree
  summary: Tree is a library for working with nested data structures.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    tree is a library for working with nested data structures.
    In a way, tree generalizes the builtin map function which only supports flat sequences, and allows to apply a function to each "leaf" preserving the overall structure.

  doc_url: https://tree.readthedocs.io/en/stable/
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - ngam
    - vnlitvinov
    - maresb
    - h-vetinari
