{% set version = "0.1.9" %}

package:
  name: dm-tree
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dm-tree/dm_tree-{{ version }}.tar.gz
  sha256: a4c7db3d3935a5a2d5e4b383fc26c6b0cd6f78c6d4605d3e7b518800ecd5342b

build:
  number: 0
  script: |
    export CMAKE_ARGS="-DUSE_SYSTEM_ABSEIL=ON -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_PYBIND11=ON"
    {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<310]


# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python
    - cmake
    - make
    - setuptools
  host:
    - pip
    - python
    - libabseil
    - pybind11
    - setuptools
  run:
    - python
    # https://github.com/google-deepmind/tree/blob/{{ version }}/setup.py
    - absl-py >=0.6.1
    - attrs >=18.2.0
    - numpy >=1.21
    - numpy >=1.21.2  # [py>=310]
    - numpy >=1.23.3  # [py>=311]
    - numpy >=1.26.0  # [py>=312]
    - numpy >=2.1.0  # [py>=313]
    - wrapt >=1.11.2

test:
  imports:
    - tree
  requires:
    - pytest
    - pip
  commands:
    - pytest --pyargs tree
    - pip check

about:
  home: https://github.com/deepmind/tree
  summary: Tree is a library for working with nested data structures.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    tree is a library for working with nested data structures.
    In a way, tree generalizes the builtin map function which only supports flat sequences, and allows to apply a function to each "leaf" preserving the overall structure.

  doc_url: https://tree.readthedocs.io/en/stable/
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - ngam
    - vnlitvinov
    - maresb
    - h-vetinari
